- name: Update apt package cache
  ansible.builtin.apt:
    update_cache: yes

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: yes


- name: Install dependencies
  ansible.builtin.apt:
    name:
      - libssl-dev 
      - zlib1g-dev 
      - libbz2-dev 
      - libreadline-dev 
      - libsqlite3-dev 
      - llvm 
      - libncursesw5-dev 
      - xz-utils 
      - tk-dev 
      - libxml2-dev 
      - libxmlsec1-dev 
      - libffi-dev 
      - liblzma-dev
    state: present  

- name: Remove existing Pyenv directory if present
  ansible.builtin.file:
    path: /root/.pyenv
    state: absent    

- name: Download pyenv installation script
  ansible.builtin.get_url:
    url: "https://pyenv.run"
    dest: "/root/pyenv_install.sh"
    mode: "055"

- name: Execute installation file 
  ansible.builtin.shell: /root/pyenv_install.sh

- name: Setup environment files 
  ansible.builtin.lineinfile:
    path: "{{ ansible_home }}/.bashrc"
    line: |
      export PYENV_ROOT="$HOME/.pyenv"
      export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init --path)"
      eval "$(pyenv init -)" 
  
- name: Execute "$SHELL" command
  ansible.builtin.shell:
    cmd: "exec \"$SHELL\""

- name: install global python version
  args:
    executable: /bin/bash
  ansible.builtin.shell:
    cmd: "pyenv install {{ global_version }}"
  vars:
    ansible_aws_ssm_timeout: 3000
  environment:
    PATH: "{{ ansible_env.HOME }}/.pyenv/bin:{{ ansible_env.PATH }}"
    
- name: Set global pyenv
  args:
    executable: /bin/bash
  ansible.builtin.shell: 
    cmd: "pyenv global {{ global_version }}"
  vars:
    ansible_aws_ssm_timeout: 3000  
  environment:
    PATH: "{{ ansible_env.HOME }}/.pyenv/bin:{{ ansible_env.PATH }}"  


- name: install local python version
  args:
    executable: /bin/bash
  ansible.builtin.shell:
    cmd: "pyenv install {{ local_version }}"
  vars:
    ansible_aws_ssm_timeout: 3000
  environment:
    PATH: "{{ ansible_env.HOME }}/.pyenv/bin:{{ ansible_env.PATH }}"
      
- name: Create new directory
  ansible.builtin.file:
    path: /root/test  
    state: directory

- name: Set local pyenv
  args:
    executable: /bin/bash
    chdir: /root/test
  ansible.builtin.shell: 
    cmd: "pyenv local {{ local_version }}"
  vars:
    ansible_aws_ssm_timeout: 3000  
  environment:
    PATH: "{{ ansible_env.HOME }}/.pyenv/bin:{{ ansible_env.PATH }}"  
      


