---
- hosts: pyenv
  become: true
  gather_facts: true
  roles:
   - pyenv
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_region: us-east-1
    ansible_aws_ssm_bucket_name: sujata-static-website-one
    
  


